// <auto-generated />
namespace ProyectoTFG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class version4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version4));
        
        string IMigrationMetadata.Id
        {
            get { return "202410161026227_version4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
